/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package appbibliotecadb.View;

import appbibliotecadb.Controller.TipoDocumentoController;
import appbibliotecadb.Dao.TipoDocumentoDAO;
import appbibliotecadb.Model.TipoDocumento;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import conection.DatabaseConnection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoseCv14
 */
public class EstudiantesForm extends javax.swing.JDialog {

    /**
     * Creates new form EstudiantesForm
     */
    private DefaultTableModel modelo;

    public int carreraIdSeleccionada;

    public EstudiantesForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Permite cerrar solo este formulario sin afectar a otros
        setLocationRelativeTo(null);

        listarTipoDocumento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDCarrera = new javax.swing.JDialog();
        txt_buscarLibroPres = new javax.swing.JTextField();
        jScrollPane18 = new javax.swing.JScrollPane();
        JTableCarreraUni = new javax.swing.JTable();
        jLabel50 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_cancelarEstudiante = new javax.swing.JButton();
        btn_NuevoEstudiante = new javax.swing.JButton();
        btn_guardarEstudiante = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtNombreCompleto1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jcbxTipoDocumento = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbxCiclo = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jcbxCiclo1 = new javax.swing.JComboBox<>();
        jcbxCiclo2 = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jcbxCiclo3 = new javax.swing.JComboBox<>();

        JTableCarreraUni.setBackground(new java.awt.Color(231, 253, 255));
        JTableCarreraUni.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JTableCarreraUni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre de la carrera Universitaria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableCarreraUni.setGridColor(new java.awt.Color(204, 204, 204));
        JTableCarreraUni.setRowHeight(30);
        JTableCarreraUni.setShowGrid(true);
        JTableCarreraUni.setShowVerticalLines(false);
        JTableCarreraUni.getTableHeader().setReorderingAllowed(false);
        JTableCarreraUni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableCarreraUniMouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(JTableCarreraUni);

        jLabel50.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel50.setText("Buscar");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Seleccione una carrera");

        javax.swing.GroupLayout jDCarreraLayout = new javax.swing.GroupLayout(jDCarrera.getContentPane());
        jDCarrera.getContentPane().setLayout(jDCarreraLayout);
        jDCarreraLayout.setHorizontalGroup(
            jDCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDCarreraLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jDCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jDCarreraLayout.createSequentialGroup()
                            .addComponent(jLabel50)
                            .addGap(10, 10, 10)
                            .addComponent(txt_buscarLibroPres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jDCarreraLayout.setVerticalGroup(
            jDCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDCarreraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(jDCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(txt_buscarLibroPres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        btn_cancelarEstudiante.setBackground(new java.awt.Color(186, 84, 77));
        btn_cancelarEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_cancelarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cancelar-24px.png"))); // NOI18N
        btn_cancelarEstudiante.setText("Cancelar   ");
        btn_cancelarEstudiante.setActionCommand("");
        btn_cancelarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cancelarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarEstudianteActionPerformed(evt);
            }
        });

        btn_NuevoEstudiante.setBackground(new java.awt.Color(78, 101, 226));
        btn_NuevoEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_NuevoEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btn_NuevoEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/nuevo_24px.png"))); // NOI18N
        btn_NuevoEstudiante.setText("Nuevo   ");
        btn_NuevoEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_NuevoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoEstudianteActionPerformed(evt);
            }
        });

        btn_guardarEstudiante.setBackground(new java.awt.Color(0, 101, 0));
        btn_guardarEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_guardarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save_24px.png"))); // NOI18N
        btn_guardarEstudiante.setText("Guardar   ");
        btn_guardarEstudiante.setToolTipText("");
        btn_guardarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btn_guardarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarEstudianteActionPerformed(evt);
            }
        });

        txtDireccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel37.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel37.setText("Dirección");

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel40.setText("Nivel/Ciclo");

        txtNombreCompleto1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel39.setText("Apellidos");

        txtNombreCompleto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel34.setText("Nombre ");

        jcbxTipoDocumento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcbxTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxTipoDocumentoActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel38.setText("Tipo Documento");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel33.setText("Documento");

        txtDocumento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setText("Telefono");

        txtTelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Ingrese los Datos a Registrar.");

        jcbxCiclo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcbxCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INI", "PRI", "SEC" }));

        jLabel42.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel42.setText("Grado/Edad");

        jcbxCiclo1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcbxCiclo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "-" }));

        jcbxCiclo2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcbxCiclo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "A", "B", "C", "D", "E", "F", "G" }));

        jLabel43.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel43.setText("Seccion");

        jLabel44.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel44.setText("Turno");

        jcbxCiclo3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcbxCiclo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "T", "N" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel39)
                            .addComponent(txtNombreCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_guardarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_NuevoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_cancelarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel42)
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jcbxCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jcbxCiclo1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jcbxCiclo2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jcbxCiclo3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(6, 6, 6)
                                .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(6, 6, 6)
                                .addComponent(txtNombreCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel36))
                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(6, 6, 6)
                        .addComponent(jcbxCiclo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel40))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jcbxCiclo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbxCiclo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jcbxCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NuevoEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxTipoDocumentoActionPerformed
        TipoDocumentoDAO tipoDocumentoDAO = new TipoDocumentoController(DatabaseConnection.getConnection());
        int selectedIndex = jcbxTipoDocumento.getSelectedIndex();
        if (selectedIndex >= 0) {
            List<TipoDocumento> tiposDocumento = tipoDocumentoDAO.readAll();
            if (selectedIndex < tiposDocumento.size()) {
                TipoDocumento selectedTipoDocumento = tiposDocumento.get(selectedIndex);
                int id = selectedTipoDocumento.getId();
                // Now you can use the id variable
                System.out.println("Selected ID: " + id);
            }
        }
    }//GEN-LAST:event_jcbxTipoDocumentoActionPerformed

    private void btn_NuevoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoEstudianteActionPerformed

    }//GEN-LAST:event_btn_NuevoEstudianteActionPerformed

    private void btn_guardarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarEstudianteActionPerformed

    }//GEN-LAST:event_btn_guardarEstudianteActionPerformed

    private void btn_cancelarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarEstudianteActionPerformed

    }//GEN-LAST:event_btn_cancelarEstudianteActionPerformed

    private void JTableCarreraUniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableCarreraUniMouseClicked
     /*   int filaSeleccionada = JTableCarreraUni.rowAtPoint(evt.getPoint());
        if (filaSeleccionada != -1) { // Verificar si se seleccionó una fila válida
            // Seleccionar la fila
            JTableCarreraUni.setRowSelectionInterval(filaSeleccionada, filaSeleccionada);
            if (SwingUtilities.isRightMouseButton(evt)) { // Verificar si se hizo clic derecho
                // Crear el menú emergente
                JPopupMenu popupMenu = new JPopupMenu();
                // Crear el ítem del menú
                JMenuItem agregarEstudianteItem = new JMenuItem("Agregar Carrera");
                // Agregar un ActionListener al ítem del menú
                agregarEstudianteItem.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        // Obtener el ID y el nombre de la carrera seleccionada
                        carreraIdSeleccionada = (int) JTableCarreraUni.getValueAt(filaSeleccionada, 0);
                        String carreraNombre = (String) JTableCarreraUni.getValueAt(filaSeleccionada, 1);
                        // Actualizar el campo lblCarrera en el formulario principal
                        lblCarrera.setText("  "+carreraNombre + carreraIdSeleccionada );

                        // Ocultar el diálogo
                        jDCarrera.setVisible(false);

                        // Mostrar un mensaje con el ID y el nombre de la carrera
                        // JOptionPane.showMessageDialog(null, "ID: " + carreraIdSeleccionada + "\nNombre: " + carreraNombre);
                    }

                });
                // Agregar el ítem al menú
                popupMenu.add(agregarEstudianteItem);
                popupMenu.show(JTableCarreraUni, evt.getX(), evt.getY());
            }
        }*/
    }//GEN-LAST:event_JTableCarreraUniMouseClicked

      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudiantesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudiantesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudiantesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudiantesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EstudiantesForm dialog = new EstudiantesForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void listarTipoDocumento() {
        TipoDocumentoDAO tipoDocumentoDAO = new TipoDocumentoController(DatabaseConnection.getConnection());
        List<TipoDocumento> tipoDocumento = tipoDocumentoDAO.readAll();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        for (TipoDocumento td : tipoDocumento) {
            modelo.addElement(td.getNombre());
        }
        jcbxTipoDocumento.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableCarreraUni;
    private javax.swing.JButton btn_NuevoEstudiante;
    private javax.swing.JButton btn_cancelarEstudiante;
    private javax.swing.JButton btn_guardarEstudiante;
    private javax.swing.JDialog jDCarrera;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JComboBox<String> jcbxCiclo;
    private javax.swing.JComboBox<String> jcbxCiclo1;
    private javax.swing.JComboBox<String> jcbxCiclo2;
    private javax.swing.JComboBox<String> jcbxCiclo3;
    private javax.swing.JComboBox<String> jcbxTipoDocumento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtNombreCompleto1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txt_buscarLibroPres;
    // End of variables declaration//GEN-END:variables
}
