/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appbibliotecadb.View;

import appbibliotecadb.Controller.EstudianteController;
import appbibliotecadb.Controller.LibroController;
import appbibliotecadb.Controller.PersonaController;
import appbibliotecadb.Controller.UsuarioController;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import appbibliotecadb.Dao.EstudianteDAO;
import appbibliotecadb.Dao.LibroDAO;
import appbibliotecadb.Dao.PersonaDAO;
import appbibliotecadb.Dao.UsuarioDao;
import appbibliotecadb.Model.Estudiante;
import appbibliotecadb.Model.Libros;
import appbibliotecadb.Model.Persona;
import appbibliotecadb.Model.Usuario;
import appbibliotecadb.Service.EstudianteService;
import appbibliotecadb.Service.LibroService;
import appbibliotecadb.Service.PersonaService;
import appbibliotecadb.Service.UsuarioService;

import java.io.IOException;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

import java.util.List;
import conection.DatabaseConnection;

/**
 *
 * @author JoseCv14
 */
public class Menu extends javax.swing.JFrame {

    private DefaultTableModel modeloEstudiantes;
    private DefaultTableModel modeloLibros;
    private DefaultTableModel modeloUsuario;

    public Menu() throws IOException {
        FlatMacLightLaf.setup();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        // Inicializar los modelos de tabla
        modeloEstudiantes = new DefaultTableModel();
        modeloLibros = new DefaultTableModel();
        modeloUsuario = new DefaultTableModel();

        //listar personas
        //listarPersonas();
        listarEstudiantes();
        listarLibros();
        listarUsuarios();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTp_Dasboart = new javax.swing.JTabbedPane();
        jP_Inicio = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblCantPrestamos = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lblCantLibros = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblCantEstudiantes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnVerReportes = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LblCantEstudiantes1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jP_Prestamos = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTablePrestamos = new javax.swing.JTable();
        btnNew_prestamo = new javax.swing.JButton();
        txt_buscar_prestamo1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jP_Libros = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnNew_libro = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        JTable_Libro = new javax.swing.JTable();
        txt_buscarLibro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jP_Estudiantes = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableEstudiante = new javax.swing.JTable();
        btnNew_estudiante = new javax.swing.JButton();
        txt_buscar_estudiante = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jP_Usuarios = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtableUsuarios = new javax.swing.JTable();
        btnNew_estudiante1 = new javax.swing.JButton();
        txt_buscar_estudiante1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jP_Reportes = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableReportesPrestamos = new javax.swing.JTable();
        btnReportePrestamos = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableReportesLibros = new javax.swing.JTable();
        btnReporteLibros = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtableReportesEstudiantes = new javax.swing.JTable();
        btnReporteEstudiantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jTp_Dasboart.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jP_Inicio.setToolTipText("");
        jP_Inicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(237, 237, 237));
        jPanel5.setToolTipText("");

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Prestamos");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/prestamo_128px.png"))); // NOI18N

        lblCantPrestamos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCantPrestamos.setForeground(new java.awt.Color(0, 0, 0));
        lblCantPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantPrestamos.setText("999999999");
        lblCantPrestamos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Libros Prestados");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantPrestamos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGap(10, 10, 10))
            .addComponent(jSeparator4)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblCantPrestamos)
                .addGap(10, 10, 10)
                .addComponent(jLabel20)
                .addGap(15, 15, 15))
        );

        jLabel18.getAccessibleContext().setAccessibleName("");

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel10.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Libros");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/libros_128px.png"))); // NOI18N

        lblCantLibros.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblCantLibros.setForeground(new java.awt.Color(0, 0, 0));
        lblCantLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantLibros.setText("999999999");
        lblCantLibros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Libros Registrados");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantLibros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(26, 26, 26)))
                .addGap(10, 10, 10))
            .addComponent(jSeparator5)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblCantLibros)
                .addGap(10, 10, 10)
                .addComponent(jLabel24)
                .addGap(15, 15, 15))
        );

        jLabel22.getAccessibleContext().setAccessibleName("");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estudiantes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/estudiantes_128px.png"))); // NOI18N

        LblCantEstudiantes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        LblCantEstudiantes.setForeground(new java.awt.Color(0, 0, 0));
        LblCantEstudiantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCantEstudiantes.setText("999999999");
        LblCantEstudiantes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estudiantes Registrados");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCantEstudiantes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGap(10, 10, 10))
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblCantEstudiantes)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleName("");

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Reportes");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/reportes_128px.png"))); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));

        btnVerReportes.setBackground(new java.awt.Color(89, 179, 144));
        btnVerReportes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnVerReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReportes.setText("ver");
        btnVerReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnVerReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnVerReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jLabel14.getAccessibleContext().setAccessibleName("");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel15.setText("Dashboard");

        btn_salir.setBackground(new java.awt.Color(247, 80, 51));
        btn_salir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/salirEx-24.png"))); // NOI18N
        btn_salir.setText("Cerrar Seción");
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema de Gestion Bibliotecario");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setInheritsPopupMenu(false);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/fondoDashboart.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuarios");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/usuario_128px.png"))); // NOI18N

        LblCantEstudiantes1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        LblCantEstudiantes1.setForeground(new java.awt.Color(0, 0, 0));
        LblCantEstudiantes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblCantEstudiantes1.setText("999999999");
        LblCantEstudiantes1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Usuarios Registrados");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblCantEstudiantes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(14, 14, 14)))
                .addGap(10, 10, 10))
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LblCantEstudiantes1)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addGap(15, 15, 15))
        );

        jLabel7.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                        .addGap(70, 70, 70))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 264, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jP_InicioLayout = new javax.swing.GroupLayout(jP_Inicio);
        jP_Inicio.setLayout(jP_InicioLayout);
        jP_InicioLayout.setHorizontalGroup(
            jP_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_InicioLayout.setVerticalGroup(
            jP_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_InicioLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTp_Dasboart.addTab("Inicio", new javax.swing.ImageIcon(getClass().getResource("/resources/images/home_24px.png")), jP_Inicio); // NOI18N

        jP_Prestamos.setToolTipText("");
        jP_Prestamos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTablePrestamos.setBackground(new java.awt.Color(231, 253, 255));
        jTablePrestamos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTablePrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Estudiante", "Cantidad", "fecha de Prestamo", "fecha de Devolucion", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePrestamos.setGridColor(new java.awt.Color(204, 204, 204));
        jTablePrestamos.setRowHeight(35);
        jTablePrestamos.setShowGrid(true);
        jTablePrestamos.setShowVerticalLines(false);
        jTablePrestamos.getTableHeader().setReorderingAllowed(false);
        jTablePrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePrestamosMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTablePrestamos);
        if (jTablePrestamos.getColumnModel().getColumnCount() > 0) {
            jTablePrestamos.getColumnModel().getColumn(0).setMinWidth(50);
            jTablePrestamos.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTablePrestamos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        btnNew_prestamo.setBackground(new java.awt.Color(105, 162, 168));
        btnNew_prestamo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnNew_prestamo.setForeground(new java.awt.Color(255, 255, 255));
        btnNew_prestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/new_24px.png"))); // NOI18N
        btnNew_prestamo.setText("Nuevo Prestamo   ");
        btnNew_prestamo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNew_prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew_prestamoActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel31.setText("Buscar");

        jLabel63.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 204, 204));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel63.setText("Listar de Prestamos / Agregar");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel63))
                    .addGroup(jPanel25Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7)
                            .addGroup(jPanel25Layout.createSequentialGroup()
                                .addComponent(btnNew_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 508, Short.MAX_VALUE)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscar_prestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel63)
                .addGap(15, 15, 15)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_buscar_prestamo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jP_PrestamosLayout = new javax.swing.GroupLayout(jP_Prestamos);
        jP_Prestamos.setLayout(jP_PrestamosLayout);
        jP_PrestamosLayout.setHorizontalGroup(
            jP_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_PrestamosLayout.setVerticalGroup(
            jP_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTp_Dasboart.addTab("Prestamos", new javax.swing.ImageIcon(getClass().getResource("/resources/images/prestamo_24px.png")), jP_Prestamos); // NOI18N

        jP_Libros.setToolTipText("");
        jP_Libros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnNew_libro.setBackground(new java.awt.Color(105, 162, 168));
        btnNew_libro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnNew_libro.setForeground(new java.awt.Color(255, 255, 255));
        btnNew_libro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/new_24px.png"))); // NOI18N
        btnNew_libro.setText("Nuevo Libro   ");
        btnNew_libro.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNew_libro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew_libroActionPerformed(evt);
            }
        });

        JTable_Libro.setBackground(new java.awt.Color(231, 253, 255));
        JTable_Libro.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        JTable_Libro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titulo", "Autor", "Editorial", "Materia", "Cantidad", "Año de Publicación", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTable_Libro.setToolTipText("");
        JTable_Libro.setGridColor(new java.awt.Color(204, 204, 204));
        JTable_Libro.setRowHeight(35);
        JTable_Libro.setShowGrid(true);
        JTable_Libro.setShowVerticalLines(false);
        JTable_Libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_LibroMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(JTable_Libro);
        if (JTable_Libro.getColumnModel().getColumnCount() > 0) {
            JTable_Libro.getColumnModel().getColumn(0).setMinWidth(40);
            JTable_Libro.getColumnModel().getColumn(0).setPreferredWidth(40);
            JTable_Libro.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        txt_buscarLibro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_buscarLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscarLibroKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Buscar");

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Listar libro / agregar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btnNew_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 508, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_buscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel30)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jP_LibrosLayout = new javax.swing.GroupLayout(jP_Libros);
        jP_Libros.setLayout(jP_LibrosLayout);
        jP_LibrosLayout.setHorizontalGroup(
            jP_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_LibrosLayout.setVerticalGroup(
            jP_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTp_Dasboart.addTab("Libros", new javax.swing.ImageIcon(getClass().getResource("/resources/images/libro_24px.png")), jP_Libros); // NOI18N

        jP_Estudiantes.setToolTipText("");
        jP_Estudiantes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel13.setBackground(new java.awt.Color(237, 237, 237));
        jPanel13.setToolTipText("");

        jTableEstudiante.setBackground(new java.awt.Color(231, 253, 255));
        jTableEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Tipo_Documento", "Documento", "Nombre", "Apellidos", "Telefono", "DIreccion", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEstudiante.setGridColor(new java.awt.Color(204, 204, 204));
        jTableEstudiante.setRowHeight(35);
        jTableEstudiante.setShowGrid(true);
        jTableEstudiante.setShowVerticalLines(false);
        jScrollPane9.setViewportView(jTableEstudiante);

        btnNew_estudiante.setBackground(new java.awt.Color(105, 162, 168));
        btnNew_estudiante.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnNew_estudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnNew_estudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/new_24px.png"))); // NOI18N
        btnNew_estudiante.setText("Nuevo Estudiante   ");
        btnNew_estudiante.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNew_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew_estudianteActionPerformed(evt);
            }
        });

        txt_buscar_estudiante.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_buscar_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_estudianteActionPerformed(evt);
            }
        });
        txt_buscar_estudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscar_estudianteKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Buscar");

        jLabel39.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 204));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("Listar Estudiantes / Agregar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(btnNew_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_buscar_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel39)
                .addGap(15, 15, 15)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jP_EstudiantesLayout = new javax.swing.GroupLayout(jP_Estudiantes);
        jP_Estudiantes.setLayout(jP_EstudiantesLayout);
        jP_EstudiantesLayout.setHorizontalGroup(
            jP_EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_EstudiantesLayout.setVerticalGroup(
            jP_EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTp_Dasboart.addTab("Estudiantes", new javax.swing.ImageIcon(getClass().getResource("/resources/images/estudiante_24px.png")), jP_Estudiantes); // NOI18N

        jP_Usuarios.setToolTipText("");
        jP_Usuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel14.setBackground(new java.awt.Color(237, 237, 237));
        jPanel14.setToolTipText("");

        jtableUsuarios.setBackground(new java.awt.Color(231, 253, 255));
        jtableUsuarios.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Id_Tipo_Documento", "Documento", "Nombre", "Apellidos", "Telefono", "DIreccion", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableUsuarios.setGridColor(new java.awt.Color(204, 204, 204));
        jtableUsuarios.setRowHeight(35);
        jtableUsuarios.setShowGrid(true);
        jtableUsuarios.setShowVerticalLines(false);
        jtableUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane10.setViewportView(jtableUsuarios);
        if (jtableUsuarios.getColumnModel().getColumnCount() > 0) {
            jtableUsuarios.getColumnModel().getColumn(0).setMinWidth(40);
            jtableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(40);
            jtableUsuarios.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        btnNew_estudiante1.setBackground(new java.awt.Color(105, 162, 168));
        btnNew_estudiante1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnNew_estudiante1.setForeground(new java.awt.Color(255, 255, 255));
        btnNew_estudiante1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/new_24px.png"))); // NOI18N
        btnNew_estudiante1.setText("Nuevo Usuario   ");
        btnNew_estudiante1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNew_estudiante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew_estudiante1ActionPerformed(evt);
            }
        });

        txt_buscar_estudiante1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txt_buscar_estudiante1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscar_estudiante1ActionPerformed(evt);
            }
        });
        txt_buscar_estudiante1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscar_estudiante1KeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Buscar");

        jLabel40.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 204));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Listar Usuarios / Agregar");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addComponent(btnNew_estudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_buscar_estudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel40)
                .addGap(15, 15, 15)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar_estudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew_estudiante1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jP_UsuariosLayout = new javax.swing.GroupLayout(jP_Usuarios);
        jP_Usuarios.setLayout(jP_UsuariosLayout);
        jP_UsuariosLayout.setHorizontalGroup(
            jP_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_UsuariosLayout.setVerticalGroup(
            jP_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTp_Dasboart.addTab("Usuarios", new javax.swing.ImageIcon(getClass().getResource("/resources/images/user.png")), jP_Usuarios); // NOI18N

        jP_Reportes.setToolTipText("");
        jP_Reportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel16.setBackground(new java.awt.Color(237, 237, 237));

        jTabbedPane1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jtableReportesPrestamos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtableReportesPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Estudiantes", "Cantidad", "Fecha de Prestamo", "Fecha de Devolucion", "Observaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableReportesPrestamos);

        btnReportePrestamos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnReportePrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/GenerarReportes-24px.png"))); // NOI18N
        btnReportePrestamos.setText("Generar Reporte de Prestamos");
        btnReportePrestamos.setEnabled(false);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(btnReportePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnReportePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Reposte de prestamos", jPanel18);

        jtableReportesLibros.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtableReportesLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "Editorial", "Materia", "Cantidad", "Año de Publicacion", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtableReportesLibros);

        btnReporteLibros.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnReporteLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/GenerarReportes-24px.png"))); // NOI18N
        btnReporteLibros.setText("Generar Reporte de Libros");
        btnReporteLibros.setEnabled(false);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(btnReporteLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnReporteLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Reporte de Libros", jPanel19);

        jtableReportesEstudiantes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtableReportesEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Documento", "Nombre y Apellidos", "telefono", "Carrera", "Direccción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtableReportesEstudiantes);

        btnReporteEstudiantes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        btnReporteEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/GenerarReportes-24px.png"))); // NOI18N
        btnReporteEstudiantes.setText("Generar Reporte de Estudiantes");
        btnReporteEstudiantes.setEnabled(false);
        btnReporteEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteEstudiantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(btnReporteEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnReporteEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Reporte de Estudiantes", jPanel20);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jTabbedPane1)
                .addGap(60, 60, 60))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jP_ReportesLayout = new javax.swing.GroupLayout(jP_Reportes);
        jP_Reportes.setLayout(jP_ReportesLayout);
        jP_ReportesLayout.setHorizontalGroup(
            jP_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jP_ReportesLayout.setVerticalGroup(
            jP_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTp_Dasboart.addTab("Reportes", new javax.swing.ImageIcon(getClass().getResource("/resources/images/reportes_24px.png")), jP_Reportes); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTp_Dasboart)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTp_Dasboart)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNew_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew_estudianteActionPerformed
        // Instancia del formulario EstudiantesForm
        EstudiantesForm estudiantesForm = new EstudiantesForm(this, true); // `this` se refiere al Frame actual, `true` indica que es modal
        // Muestra el formulario
        estudiantesForm.setVisible(true);


    }//GEN-LAST:event_btnNew_estudianteActionPerformed

    private void btnNew_libroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew_libroActionPerformed
        // Instancia del formulario librosForm
        LibrosForm librosForm = new LibrosForm(this, true); // `this` se refiere al Frame actual, `true` indica que es modal
        // Muestra el formulario
        librosForm.setVisible(true);

    }//GEN-LAST:event_btnNew_libroActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // Configura el mensaje de confirmación con un tamaño de fuente más grande
        JLabel mensaje = new JLabel("<html><p style='font-size:14pt;'>¿Estás seguro de que deseas salir?</p></html>");

        JOptionPane optionPane = new JOptionPane(mensaje, JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION);

        // Crea el diálogo personalizado y establece su tamaño
        JDialog dialog = optionPane.createDialog("Confirmación");
        //dialog.setSize(400, 200); // Tamaño personalizado (ancho x alto)

        // Desactiva el botón de cerrar en el diálogo
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

        dialog.setVisible(true);

        // Obtiene la opción seleccionada por el usuario
        Object selectedValue = optionPane.getValue();
        if (selectedValue.equals(JOptionPane.YES_OPTION)) {
            // Si el usuario confirma que quiere salir, cierra la sesión y regresa al login
            dispose(); // Cierra el menú
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btnNew_prestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew_prestamoActionPerformed
        // Instancia del formulario prestamos form
        PrestamosForm prestamosForm = new PrestamosForm(this, true); // `this` se refiere al Frame actual, `true` indica que es modal
        // Muestra el formulario
        prestamosForm.setVisible(true);
    }//GEN-LAST:event_btnNew_prestamoActionPerformed

    private void btnVerReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReportesActionPerformed

    }//GEN-LAST:event_btnVerReportesActionPerformed

    private void txt_buscar_estudianteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_estudianteKeyPressed
        txt_buscar_estudiante.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                // buscarEstudiantes();

            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                //buscarEstudiantes();

            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                //buscarEstudiantes();

            }
        });
    }//GEN-LAST:event_txt_buscar_estudianteKeyPressed

    private void jTablePrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePrestamosMouseClicked

    }//GEN-LAST:event_jTablePrestamosMouseClicked

    private void JTable_LibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_LibroMouseClicked

    }//GEN-LAST:event_JTable_LibroMouseClicked

    private void txt_buscarLibroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarLibroKeyPressed

    }//GEN-LAST:event_txt_buscarLibroKeyPressed

    private void btnReporteEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteEstudiantesActionPerformed


    }//GEN-LAST:event_btnReporteEstudiantesActionPerformed

    private void txt_buscar_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_estudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_estudianteActionPerformed

    private void btnNew_estudiante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew_estudiante1ActionPerformed
        // Instancia del formulario prestamos form
        UsuariosForm usuariosForm = new UsuariosForm(this, true); // `this` se refiere al Frame actual, `true` indica que es modal
        // Muestra el formulario
        usuariosForm.setVisible(true);
    }//GEN-LAST:event_btnNew_estudiante1ActionPerformed

    private void txt_buscar_estudiante1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscar_estudiante1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_estudiante1ActionPerformed

    private void txt_buscar_estudiante1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_estudiante1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscar_estudiante1KeyPressed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

    }

    //==========================================================================   
    //Estudiantes
    //==========================================================================
    private void listarEstudiantes() {
        modeloEstudiantes.addColumn("Id");
        modeloEstudiantes.addColumn("Codigo");
        modeloEstudiantes.addColumn("Nombre y Apellidos");
        modeloEstudiantes.addColumn("Documento");
        modeloEstudiantes.addColumn("Telefono");
        modeloEstudiantes.addColumn("Dirección");
        modeloEstudiantes.addColumn("Nivel/Ciclo");
        modeloEstudiantes.addColumn("Grado/Edad");
        modeloEstudiantes.addColumn("Sección");
        modeloEstudiantes.addColumn("Turno");
        modeloEstudiantes.addColumn("Estado");

        jTableEstudiante.setModel(modeloEstudiantes);
        EstudianteDAO estudianteDAO = new EstudianteController(DatabaseConnection.getConnection());
        EstudianteService estudianteService = new EstudianteService(estudianteDAO);
        List<Estudiante> estudiantes = estudianteService.readAll();
        if (estudiantes.size() > 0) {
            SwingUtilities.invokeLater(() -> {
                for (Estudiante p : estudiantes) {
                    Object[] fila = new Object[10];
                    fila[0] = p.getId();
                    fila[1] = p.getCodigo();
                    fila[2] = p.getNombre_completo();
                    fila[3] = p.getTelefono();
                    fila[4] = p.getDireccion();
                    fila[5] = p.getNivel_Ciclo();
                    fila[6] = p.getGrado_Edad();
                    fila[7] = p.getSeccion();
                    fila[8] = p.getTurno();
                    fila[9] = p.getEstado();

                    modeloEstudiantes.addRow(fila);
                }
                // Ocultar la columna ID
                jTableEstudiante.getColumnModel().getColumn(0).setMinWidth(0);
                jTableEstudiante.getColumnModel().getColumn(0).setMaxWidth(0);
                jTableEstudiante.getColumnModel().getColumn(0).setWidth(0);
                jTableEstudiante.getColumnModel().getColumn(0).setPreferredWidth(0);
            });
        } else {
            System.out.println("La lista de estudiantes está vacía.");
        }
    }
    //==========================================================================
    //fin de estudiantes 
    //==========================================================================

    //==========================================================================
    //Libros
    //==========================================================================
    private void listarLibros() {
        modeloLibros.addColumn("Id");
        modeloLibros.addColumn("Titulo");
        modeloLibros.addColumn("Autor");
        modeloLibros.addColumn("Editorial");
        modeloLibros.addColumn("Categoria");
        modeloLibros.addColumn("Cantidad");
        modeloLibros.addColumn("Fecha de Publicación");
        modeloLibros.addColumn("Estado");

        JTable_Libro.setModel(modeloLibros);
        LibroDAO libroDAO = new LibroController(DatabaseConnection.getConnection());
        LibroService libroService = new LibroService(libroDAO);
        List<Libros> libros = libroService.listAll();
        if (libros.size() > 0) {
            SwingUtilities.invokeLater(() -> {
                for (Libros p : libros) {
                    Object[] fila = new Object[8];
                    fila[0] = p.getId();
                    fila[1] = p.getTitulo();
                    fila[2] = p.getNombre_Autor();
                    fila[3] = p.getEditorial();
                    fila[4] = p.getCategoria();
                    fila[5] = p.getCantidad();
                    fila[6] = p.getA_publicacion();
                    fila[7] = p.getEstado();

                    modeloLibros.addRow(fila);
                }
                // Ocultar la columna ID
                JTable_Libro.getColumnModel().getColumn(0).setMinWidth(0);
                JTable_Libro.getColumnModel().getColumn(0).setMaxWidth(0);
                JTable_Libro.getColumnModel().getColumn(0).setWidth(0);
                JTable_Libro.getColumnModel().getColumn(0).setPreferredWidth(0);
            });
        } else {
            System.out.println("La lista de libros está vacía.");
        }
    }
    //==========================================================================
    //fin de libros 
    //==========================================================================

    //==========================================================================
    //Usuarios
    //==========================================================================
    private void listarUsuarios() {
        modeloUsuario.addColumn("Id");
        modeloUsuario.addColumn("nombre_completo");
        modeloUsuario.addColumn("documento");
        modeloUsuario.addColumn("telefono");
        modeloUsuario.addColumn("rol_nombre");
        modeloUsuario.addColumn("usuario");
        modeloUsuario.addColumn("contraseña");
        modeloUsuario.addColumn("Estado");

        jtableUsuarios.setModel(modeloUsuario);
        UsuarioDao usuarioDAO = new UsuarioController(DatabaseConnection.getConnection());
        UsuarioService usuarioService = new UsuarioService(usuarioDAO);
        List<Usuario> usuarios = usuarioService.listAll();
        if (usuarios.size() > 0) {
            SwingUtilities.invokeLater(() -> {
                for (Usuario p : usuarios) {
                    Object[] fila = new Object[8];
                    fila[0] = p.getId();
                    fila[1] = p.getNombre_completo();
                    fila[2] = p.getT_documento();
                    fila[3] = p.getTelefono();
                    fila[4] = p.getRol_nombre();
                    fila[5] = p.getUsuario();
                    fila[6] = p.getContraseña();
                    fila[7] = p.getEstado();

                    modeloUsuario.addRow(fila);
                }               
                // Ocultar la columna ID
                jtableUsuarios.getColumnModel().getColumn(0).setMinWidth(0);
                jtableUsuarios.getColumnModel().getColumn(0).setMaxWidth(0);
                jtableUsuarios.getColumnModel().getColumn(0).setWidth(0);
                jtableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(0);
            });
        } else {
            System.out.println("La lista de libros está vacía.");
        }
    }

    //==========================================================================
    //fin de Usuarios
    //==========================================================================

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable_Libro;
    private javax.swing.JLabel LblCantEstudiantes;
    private javax.swing.JLabel LblCantEstudiantes1;
    private javax.swing.JButton btnNew_estudiante;
    private javax.swing.JButton btnNew_estudiante1;
    private javax.swing.JButton btnNew_libro;
    private javax.swing.JButton btnNew_prestamo;
    private javax.swing.JButton btnReporteEstudiantes;
    private javax.swing.JButton btnReporteLibros;
    private javax.swing.JButton btnReportePrestamos;
    private javax.swing.JButton btnVerReportes;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jP_Estudiantes;
    private javax.swing.JPanel jP_Inicio;
    private javax.swing.JPanel jP_Libros;
    private javax.swing.JPanel jP_Prestamos;
    private javax.swing.JPanel jP_Reportes;
    private javax.swing.JPanel jP_Usuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableEstudiante;
    private javax.swing.JTable jTablePrestamos;
    private javax.swing.JTabbedPane jTp_Dasboart;
    private javax.swing.JTable jtableReportesEstudiantes;
    private javax.swing.JTable jtableReportesLibros;
    private javax.swing.JTable jtableReportesPrestamos;
    private javax.swing.JTable jtableUsuarios;
    private javax.swing.JLabel lblCantLibros;
    private javax.swing.JLabel lblCantPrestamos;
    private javax.swing.JTextField txt_buscarLibro;
    private javax.swing.JTextField txt_buscar_estudiante;
    private javax.swing.JTextField txt_buscar_estudiante1;
    private javax.swing.JTextField txt_buscar_prestamo1;
    // End of variables declaration//GEN-END:variables

}
